apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090  # Substitua com o endereço do seu Prometheus
    isDefault: true
    jsonData:
      timeInterval: "10s"
